import '../styles/globals.scss';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
   title: 'Nikita Panasevych',
   description: 'Generated by create next app',
   icon: '../public/favicon.ico',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <head>
            <meta charSet="utf-8" />
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
            <link rel="icon" href={metadata.icon} type="image/x-icon" sizes="any" />
         </head>
         <body className={inter.className}>{children}</body>
      </html>
   );
}
